import { db } from "~/server/db";
import {
  Construcciones,
  NumeroFincas,
  Sedes,
  UsosActuales,
} from "~/server/db/schema"; // Asegúrate de importar la tabla que creaste

export async function insertarDatos() {
    const dataSede = {
        nombre: "CAMPUS TECNOLÓGICO LOCAL SAN JOSÉ",
    }
  
    const dataNumeroFinca = [
        { numero: "FR-1-073967A-000" },
        { numero: "FR-1333791-000" },
        { numero: "FR-1-70536-00" },
        { numero: "1-112539-000 1-119085-0000" },
    ];
  
    const data = [
        {
          codigoEdificio: "SJ01",
          sede: 3,
          esRenovacion: false,
          nombre: "Edificio Rafles (5 Niveles)",
          fechaConstruccion: 1960,
          noFinca: 3,
          m2Construccion: 1898.65,
          valorDolarPorM2: "1285.0",
          valorColonPorM2: "790082.25",
          edadAl2021: 61,
          vidaUtilHacienda: 50,
          vidaUtilExperto: 30,
          valorEdificioIR: "2439765.25",
          depreciacionLinealAnual: "48795.305",
          valorActualRevaluado: "1463859.15",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ01",
          sede: 3,
          esRenovacion: false,
          nombre: "Aceras Perimetrales",
          fechaConstruccion: 1960,
          noFinca: 3,
          m2Construccion: 111.1,
          valorDolarPorM2: "30.54",
          valorColonPorM2: "18777.519",
          edadAl2021: 61,
          vidaUtilHacienda: 15,
          vidaUtilExperto: 5,
          valorEdificioIR: "3392.9939999999997",
          depreciacionLinealAnual: "226.19959999999998",
          valorActualRevaluado: "1130.9979999999998",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ01",
          sede: 3,
          esRenovacion: false,
          nombre: "Porción de Zonas verdes",
          fechaConstruccion: 1960,
          noFinca: 3,
          m2Construccion: 0.0,
          valorDolarPorM2: "3.4",
          valorColonPorM2: "2090.4900000000002",
          edadAl2021: 61,
          vidaUtilHacienda: 10,
          vidaUtilExperto: 5,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ01",
          sede: 3,
          esRenovacion: false,
          nombre: "Terreno  (Huella)",
          fechaConstruccion: 1960,
          noFinca: 3,
          m2Construccion: 373.45,
          valorDolarPorM2: "565.9071650051915",
          valorColonPorM2: "347948.020403442",
          edadAl2021: null,
          vidaUtilHacienda: null,
          vidaUtilExperto: null,
          valorEdificioIR: null,
          depreciacionLinealAnual: null,
          valorActualRevaluado: null,
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ02",
          sede: 3,
          esRenovacion: false,
          nombre: "Edificio de La Escuela de Arquitectura y Urbanismo (Incluye Readecuación Sísmica, Remodelación, Ducto y Elevador, aspectos de seguridad 2010,2011)  (3 Niveles)",
          fechaConstruccion: 1968,
          noFinca: 4,
          m2Construccion: 1374.15,
          valorDolarPorM2: "1600.0",
          valorColonPorM2: "983760.0",
          edadAl2021: 53,
          vidaUtilHacienda: 50,
          vidaUtilExperto: 30,
          valorEdificioIR: "2198640",
          depreciacionLinealAnual: "43972.8",
          valorActualRevaluado: "1319184",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ02",
          sede: 3,
          esRenovacion: false,
          nombre: "Aceras Perimetrales",
          fechaConstruccion: 1968,
          noFinca: 4,
          m2Construccion: 105.44,
          valorDolarPorM2: "30.54",
          valorColonPorM2: "18777.519",
          edadAl2021: 53,
          vidaUtilHacienda: 15,
          vidaUtilExperto: 5,
          valorEdificioIR: "3220.1376",
          depreciacionLinealAnual: "214.67584",
          valorActualRevaluado: "1073.3791999999999",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ02",
          sede: 3,
          esRenovacion: false,
          nombre: "Porción de Zonas verdes (No Aplica)",
          fechaConstruccion: 1968,
          noFinca: 4,
          m2Construccion: 0.0,
          valorDolarPorM2: "0.0",
          valorColonPorM2: "0.0",
          edadAl2021: 0,
          vidaUtilHacienda: 0,
          vidaUtilExperto: 0,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: null,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ02",
          sede: 3,
          esRenovacion: false,
          nombre: "Terreno  (Huella)",
          fechaConstruccion: 1968,
          noFinca: 4,
          m2Construccion: 374.98,
          valorDolarPorM2: "565.1441430601532",
          valorColonPorM2: "347478.8763605352",
          edadAl2021: null,
          vidaUtilHacienda: null,
          vidaUtilExperto: null,
          valorEdificioIR: null,
          depreciacionLinealAnual: null,
          valorActualRevaluado: null,
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ03",
          sede: 3,
          esRenovacion: false,
          nombre: "Edificio Administrativo y de Servicios (3 Niveles)",
          fechaConstruccion: 1980,
          noFinca: null,
          m2Construccion: 673.44,
          valorDolarPorM2: "1100.0",
          valorColonPorM2: "676335.0",
          edadAl2021: 41,
          vidaUtilHacienda: 50,
          vidaUtilExperto: 30,
          valorEdificioIR: "740784.0000000001",
          depreciacionLinealAnual: "14815.680000000002",
          valorActualRevaluado: "444470.4000000001",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ03",
          sede: 3,
          esRenovacion: false,
          nombre: "Aceras Perimetrales",
          fechaConstruccion: 1980,
          noFinca: null,
          m2Construccion: 0.0,
          valorDolarPorM2: "30.54",
          valorColonPorM2: "18777.519",
          edadAl2021: 41,
          vidaUtilHacienda: 15,
          vidaUtilExperto: 5,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ03",
          sede: 3,
          esRenovacion: false,
          nombre: "Porción de Zonas verdes (No Aplica)",
          fechaConstruccion: 1980,
          noFinca: null,
          m2Construccion: 0.0,
          valorDolarPorM2: "0.0",
          valorColonPorM2: "0.0",
          edadAl2021: 0,
          vidaUtilHacienda: 0,
          vidaUtilExperto: 0,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: null,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ03",
          sede: 3,
          esRenovacion: false,
          nombre: "Terreno  (Huella)",
          fechaConstruccion: 1980,
          noFinca: null,
          m2Construccion: 271.55,
          valorDolarPorM2: "628.6536903448847",
          valorColonPorM2: "386527.7215085524",
          edadAl2021: null,
          vidaUtilHacienda: null,
          vidaUtilExperto: null,
          valorEdificioIR: null,
          depreciacionLinealAnual: null,
          valorActualRevaluado: null,
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ04",
          sede: 3,
          esRenovacion: false,
          nombre: "Casa Azul (1 Nivel y Ático) *",
          fechaConstruccion: 1970,
          noFinca: null,
          m2Construccion: 270.36,
          valorDolarPorM2: "1700.0",
          valorColonPorM2: "1045245.0",
          edadAl2021: 51,
          vidaUtilHacienda: 50,
          vidaUtilExperto: 30,
          valorEdificioIR: "459612",
          depreciacionLinealAnual: "9192.24",
          valorActualRevaluado: "275767.2",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ04",
          sede: 3,
          esRenovacion: false,
          nombre: "Aceras Perimetrales",
          fechaConstruccion: 1970,
          noFinca: null,
          m2Construccion: 0.0,
          valorDolarPorM2: "30.54",
          valorColonPorM2: "18777.519",
          edadAl2021: 51,
          vidaUtilHacienda: 15,
          vidaUtilExperto: 5,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ04",
          sede: 3,
          esRenovacion: false,
          nombre: "Porción de Zonas verdes (No Aplica)",
          fechaConstruccion: 1970,
          noFinca: null,
          m2Construccion: 0.0,
          valorDolarPorM2: "0.0",
          valorColonPorM2: "0.0",
          edadAl2021: 0,
          vidaUtilHacienda: 0,
          vidaUtilExperto: 0,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: null,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ04",
          sede: 3,
          esRenovacion: false,
          nombre: "Terreno  (Huella)",
          fechaConstruccion: 1970,
          noFinca: null,
          m2Construccion: 233.16,
          valorDolarPorM2: "661.083123312187",
          valorColonPorM2: "406466.9583684982",
          edadAl2021: null,
          vidaUtilHacienda: null,
          vidaUtilExperto: null,
          valorEdificioIR: null,
          depreciacionLinealAnual: null,
          valorActualRevaluado: null,
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ05",
          sede: 3,
          esRenovacion: false,
          nombre: "Casa Verde (2 Niveles) *",
          fechaConstruccion: 1970,
          noFinca: null,
          m2Construccion: 735.3,
          valorDolarPorM2: "450.0",
          valorColonPorM2: "276682.5",
          edadAl2021: 51,
          vidaUtilHacienda: 50,
          vidaUtilExperto: 30,
          valorEdificioIR: "330885",
          depreciacionLinealAnual: "6617.7",
          valorActualRevaluado: "198531",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ05",
          sede: 3,
          esRenovacion: false,
          nombre: "Aceras Perimetrales",
          fechaConstruccion: 1970,
          noFinca: null,
          m2Construccion: 0.0,
          valorDolarPorM2: "30.54",
          valorColonPorM2: "18777.519",
          edadAl2021: 51,
          vidaUtilHacienda: 15,
          vidaUtilExperto: 5,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ05",
          sede: 3,
          esRenovacion: false,
          nombre: "Porción de Zonas verdes",
          fechaConstruccion: 1970,
          noFinca: null,
          m2Construccion: 177.73,
          valorDolarPorM2: "3.4",
          valorColonPorM2: "2090.4900000000002",
          edadAl2021: 51,
          vidaUtilHacienda: 10,
          vidaUtilExperto: 5,
          valorEdificioIR: "604.2819999999999",
          depreciacionLinealAnual: "60.42819999999999",
          valorActualRevaluado: "302.14099999999996",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ05",
          sede: 3,
          esRenovacion: false,
          nombre: "Terreno  (Huella)",
          fechaConstruccion: 1970,
          noFinca: null,
          m2Construccion: 414.27,
          valorDolarPorM2: "546.8627673380197",
          valorColonPorM2: "336238.5724977814",
          edadAl2021: null,
          vidaUtilHacienda: null,
          vidaUtilExperto: null,
          valorEdificioIR: null,
          depreciacionLinealAnual: null,
          valorActualRevaluado: null,
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ06",
          sede: 3,
          esRenovacion: false,
          nombre: "Biblioteca y Aulas (4 Niveles)",
          fechaConstruccion: 2017,
          noFinca: 3,
          m2Construccion: 1942.41,
          valorDolarPorM2: "860.0",
          valorColonPorM2: "528771.0",
          edadAl2021: 4,
          vidaUtilHacienda: 50,
          vidaUtilExperto: 46,
          valorEdificioIR: "1670472.6",
          depreciacionLinealAnual: "33409.452000000005",
          valorActualRevaluado: "1536834.7920000001",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ06",
          sede: 3,
          esRenovacion: false,
          nombre: "Aceras Perimetrales",
          fechaConstruccion: 2017,
          noFinca: 3,
          m2Construccion: 13.09,
          valorDolarPorM2: "30.54",
          valorColonPorM2: "18777.519",
          edadAl2021: 4,
          vidaUtilHacienda: 15,
          vidaUtilExperto: 12,
          valorEdificioIR: "399.7686",
          depreciacionLinealAnual: "26.651239999999998",
          valorActualRevaluado: "319.81487999999996",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ06",
          sede: 3,
          esRenovacion: false,
          nombre: "Porción de Zonas verdes",
          fechaConstruccion: 2017,
          noFinca: 3,
          m2Construccion: 0.0,
          valorDolarPorM2: "3.4",
          valorColonPorM2: "2090.4900000000002",
          edadAl2021: 4,
          vidaUtilHacienda: 10,
          vidaUtilExperto: 10,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ06",
          sede: 3,
          esRenovacion: false,
          nombre: "Terreno  (Huella)",
          fechaConstruccion: 2017,
          noFinca: 3,
          m2Construccion: 803.09,
          valorDolarPorM2: "439.5514465797365",
          valorColonPorM2: "270258.206929551",
          edadAl2021: null,
          vidaUtilHacienda: null,
          vidaUtilExperto: null,
          valorEdificioIR: null,
          depreciacionLinealAnual: null,
          valorActualRevaluado: null,
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ07",
          sede: 3,
          esRenovacion: false,
          nombre: "Casa Rosada (1 nivel)",
          fechaConstruccion: 1965,
          noFinca: 5,
          m2Construccion: 346.13,
          valorDolarPorM2: "650.0",
          valorColonPorM2: "399652.5",
          edadAl2021: 56,
          vidaUtilHacienda: 50,
          vidaUtilExperto: 30,
          valorEdificioIR: "224984.5",
          depreciacionLinealAnual: "4499.69",
          valorActualRevaluado: "134990.69999999998",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ07",
          sede: 3,
          esRenovacion: false,
          nombre: "Aceras Perimetrales",
          fechaConstruccion: 1965,
          noFinca: 5,
          m2Construccion: 13.09,
          valorDolarPorM2: "30.54",
          valorColonPorM2: "18777.519",
          edadAl2021: 56,
          vidaUtilHacienda: 15,
          vidaUtilExperto: 5,
          valorEdificioIR: "399.7686",
          depreciacionLinealAnual: "26.651239999999998",
          valorActualRevaluado: "133.25619999999998",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ07",
          sede: 3,
          esRenovacion: false,
          nombre: "Porción de Zonas verdes",
          fechaConstruccion: 1965,
          noFinca: 5,
          m2Construccion: 0.0,
          valorDolarPorM2: "3.4",
          valorColonPorM2: "2090.4900000000002",
          edadAl2021: 56,
          vidaUtilHacienda: 10,
          vidaUtilExperto: 5,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ07",
          sede: 3,
          esRenovacion: false,
          nombre: "Terreno  (Huella)",
          fechaConstruccion: 1965,
          noFinca: 5,
          m2Construccion: 297.07,
          valorDolarPorM2: "610.2931605290521",
          valorColonPorM2: "375238.7497512877",
          edadAl2021: null,
          vidaUtilHacienda: null,
          vidaUtilExperto: null,
          valorEdificioIR: null,
          depreciacionLinealAnual: null,
          valorActualRevaluado: null,
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ08",
          sede: 3,
          esRenovacion: false,
          nombre: "Casa Cultural Amon y S.S. (1 Nivel)",
          fechaConstruccion: 1978,
          noFinca: 3,
          m2Construccion: 250.06,
          valorDolarPorM2: "800.0",
          valorColonPorM2: "491880.0",
          edadAl2021: 43,
          vidaUtilHacienda: 50,
          vidaUtilExperto: 30,
          valorEdificioIR: "200048",
          depreciacionLinealAnual: "4000.96",
          valorActualRevaluado: "120028.8",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ08",
          sede: 3,
          esRenovacion: false,
          nombre: "Aceras Perimetrales",
          fechaConstruccion: 1978,
          noFinca: 3,
          m2Construccion: 0.0,
          valorDolarPorM2: "30.54",
          valorColonPorM2: "18777.519",
          edadAl2021: 43,
          vidaUtilHacienda: 15,
          vidaUtilExperto: 5,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ08",
          sede: 3,
          esRenovacion: false,
          nombre: "Porción de Zonas verdes",
          fechaConstruccion: 1978,
          noFinca: 3,
          m2Construccion: 0.0,
          valorDolarPorM2: "3.4",
          valorColonPorM2: "2090.4900000000002",
          edadAl2021: 43,
          vidaUtilHacienda: 10,
          vidaUtilExperto: 5,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ08",
          sede: 3,
          esRenovacion: false,
          nombre: "Terreno  (Huella)",
          fechaConstruccion: 1978,
          noFinca: 3,
          m2Construccion: 250.06,
          valorDolarPorM2: "645.992254503476",
          valorColonPorM2: "397188.33768146223",
          edadAl2021: null,
          vidaUtilHacienda: null,
          vidaUtilExperto: null,
          valorEdificioIR: null,
          depreciacionLinealAnual: null,
          valorActualRevaluado: null,
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ09",
          sede: 3,
          esRenovacion: false,
          nombre: "Casa Pacheco  (1 Nivel) *",
          fechaConstruccion: 1970,
          noFinca: 6,
          m2Construccion: 1078.99,
          valorDolarPorM2: "450.0",
          valorColonPorM2: "276682.5",
          edadAl2021: 51,
          vidaUtilHacienda: 50,
          vidaUtilExperto: 30,
          valorEdificioIR: "485545.5",
          depreciacionLinealAnual: "9710.91",
          valorActualRevaluado: "291327.3",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ09",
          sede: 3,
          esRenovacion: false,
          nombre: "Aceras Perimetrales",
          fechaConstruccion: 1970,
          noFinca: 6,
          m2Construccion: 0.0,
          valorDolarPorM2: "30.54",
          valorColonPorM2: "18777.519",
          edadAl2021: 51,
          vidaUtilHacienda: 15,
          vidaUtilExperto: 5,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ09",
          sede: 3,
          esRenovacion: false,
          nombre: "Porción de Zonas verdes",
          fechaConstruccion: 1970,
          noFinca: 6,
          m2Construccion: 0.0,
          valorDolarPorM2: "3.4",
          valorColonPorM2: "2090.4900000000002",
          edadAl2021: 51,
          vidaUtilHacienda: 10,
          vidaUtilExperto: 5,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ09",
          sede: 3,
          esRenovacion: false,
          nombre: "Terreno  (Huella)",
          fechaConstruccion: 1970,
          noFinca: 6,
          m2Construccion: 694.07,
          valorDolarPorM2: "461.23135721635407",
          valorColonPorM2: "283588.0999844753",
          edadAl2021: null,
          vidaUtilHacienda: null,
          vidaUtilExperto: null,
          valorEdificioIR: null,
          depreciacionLinealAnual: null,
          valorActualRevaluado: null,
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ10",
          sede: 3,
          esRenovacion: false,
          nombre: "Gimnasio Multiuso",
          fechaConstruccion: 2005,
          noFinca: 3,
          m2Construccion: 134.5,
          valorDolarPorM2: "150.0",
          valorColonPorM2: "92227.5",
          edadAl2021: 16,
          vidaUtilHacienda: 50,
          vidaUtilExperto: 35,
          valorEdificioIR: "20175",
          depreciacionLinealAnual: "403.5",
          valorActualRevaluado: "14122.5",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ10",
          sede: 3,
          esRenovacion: false,
          nombre: "Aceras Perimetrales",
          fechaConstruccion: 2005,
          noFinca: 3,
          m2Construccion: 0.0,
          valorDolarPorM2: "30.54",
          valorColonPorM2: "18777.519",
          edadAl2021: 16,
          vidaUtilHacienda: 15,
          vidaUtilExperto: 10,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ10",
          sede: 3,
          esRenovacion: false,
          nombre: "Porción de Zonas verdes",
          fechaConstruccion: 2005,
          noFinca: 3,
          m2Construccion: 0.0,
          valorDolarPorM2: "3.4",
          valorColonPorM2: "2090.4900000000002",
          edadAl2021: 16,
          vidaUtilHacienda: 10,
          vidaUtilExperto: 6,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ10",
          sede: 3,
          esRenovacion: false,
          nombre: "Terreno  (Huella)",
          fechaConstruccion: 2005,
          noFinca: 3,
          m2Construccion: 134.5,
          valorDolarPorM2: "792.6903145676945",
          valorColonPorM2: "487385.63991194696",
          edadAl2021: null,
          vidaUtilHacienda: null,
          vidaUtilExperto: null,
          valorEdificioIR: null,
          depreciacionLinealAnual: null,
          valorActualRevaluado: null,
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ11",
          sede: 3,
          esRenovacion: false,
          nombre: "Soda ",
          fechaConstruccion: 1978,
          noFinca: 3,
          m2Construccion: 132.83,
          valorDolarPorM2: "800.0",
          valorColonPorM2: "491880.0",
          edadAl2021: 43,
          vidaUtilHacienda: 50,
          vidaUtilExperto: 30,
          valorEdificioIR: "106264.00000000001",
          depreciacionLinealAnual: "2125.28",
          valorActualRevaluado: "63758.40000000001",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ11",
          sede: 3,
          esRenovacion: false,
          nombre: "Aceras Perimetrales",
          fechaConstruccion: 1978,
          noFinca: 3,
          m2Construccion: 0.0,
          valorDolarPorM2: "30.54",
          valorColonPorM2: "18777.519",
          edadAl2021: 43,
          vidaUtilHacienda: 15,
          vidaUtilExperto: 5,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ11",
          sede: 3,
          esRenovacion: false,
          nombre: "Porción de Zonas verdes",
          fechaConstruccion: 1978,
          noFinca: 3,
          m2Construccion: 0.0,
          valorDolarPorM2: "3.4",
          valorColonPorM2: "2090.4900000000002",
          edadAl2021: 43,
          vidaUtilHacienda: 10,
          vidaUtilExperto: 5,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ11",
          sede: 3,
          esRenovacion: false,
          nombre: "Terreno  (Huella)",
          fechaConstruccion: 1978,
          noFinca: 3,
          m2Construccion: 132.83,
          valorDolarPorM2: "795.9653614828056",
          valorColonPorM2: "489399.3025077031",
          edadAl2021: null,
          vidaUtilHacienda: null,
          vidaUtilExperto: null,
          valorEdificioIR: null,
          depreciacionLinealAnual: null,
          valorActualRevaluado: null,
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ12",
          sede: 3,
          esRenovacion: false,
          nombre: "Caseta de Vigilancia",
          fechaConstruccion: 1978,
          noFinca: 3,
          m2Construccion: 34.5,
          valorDolarPorM2: "1100.0",
          valorColonPorM2: "676335.0",
          edadAl2021: 43,
          vidaUtilHacienda: 50,
          vidaUtilExperto: 30,
          valorEdificioIR: "37950",
          depreciacionLinealAnual: "759",
          valorActualRevaluado: "22770",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ12",
          sede: 3,
          esRenovacion: false,
          nombre: "Aceras Perimetrales",
          fechaConstruccion: 1978,
          noFinca: 3,
          m2Construccion: 40.2,
          valorDolarPorM2: "30.54",
          valorColonPorM2: "18777.519",
          edadAl2021: 43,
          vidaUtilHacienda: 15,
          vidaUtilExperto: 5,
          valorEdificioIR: "1227.708",
          depreciacionLinealAnual: "81.8472",
          valorActualRevaluado: "409.236",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ12",
          sede: 3,
          esRenovacion: false,
          nombre: "Porción de Zonas verdes",
          fechaConstruccion: 1978,
          noFinca: 3,
          m2Construccion: 0.0,
          valorDolarPorM2: "3.4",
          valorColonPorM2: "2090.4900000000002",
          edadAl2021: 43,
          vidaUtilHacienda: 10,
          vidaUtilExperto: 5,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ12",
          sede: 3,
          esRenovacion: false,
          nombre: "Terreno  (Huella)",
          fechaConstruccion: 1978,
          noFinca: 3,
          m2Construccion: 34.5,
          valorDolarPorM2: "1241.9428292543375",
          valorColonPorM2: "763608.5485670294",
          edadAl2021: null,
          vidaUtilHacienda: null,
          vidaUtilExperto: null,
          valorEdificioIR: null,
          depreciacionLinealAnual: null,
          valorActualRevaluado: null,
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ13",
          sede: 3,
          esRenovacion: false,
          nombre: "Plazoleta",
          fechaConstruccion: null,
          noFinca: 3,
          m2Construccion: 280.59,
          valorDolarPorM2: "200.0",
          valorColonPorM2: "122970.0",
          edadAl2021: 2021,
          vidaUtilHacienda: 50,
          vidaUtilExperto: 30,
          valorEdificioIR: "56117.99999999999",
          depreciacionLinealAnual: "1122.36",
          valorActualRevaluado: "33670.799999999996",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ13",
          sede: 3,
          esRenovacion: false,
          nombre: "Aceras Perimetrales",
          fechaConstruccion: null,
          noFinca: 3,
          m2Construccion: 0.0,
          valorDolarPorM2: "30.54",
          valorColonPorM2: "18777.519",
          edadAl2021: 2021,
          vidaUtilHacienda: 15,
          vidaUtilExperto: 5,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ13",
          sede: 3,
          esRenovacion: false,
          nombre: "Porción de Zonas verdes",
          fechaConstruccion: null,
          noFinca: 3,
          m2Construccion: 99.31,
          valorDolarPorM2: "3.4",
          valorColonPorM2: "2090.4900000000002",
          edadAl2021: 2021,
          vidaUtilHacienda: 10,
          vidaUtilExperto: 5,
          valorEdificioIR: "337.654",
          depreciacionLinealAnual: "33.7654",
          valorActualRevaluado: "168.827",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "SJ13",
          sede: 3,
          esRenovacion: false,
          nombre: "Terreno  (Huella)",
          fechaConstruccion: null,
          noFinca: 3,
          m2Construccion: 280.59,
          valorDolarPorM2: "621.8964579490549",
          valorColonPorM2: "382373.03716997645",
          edadAl2021: null,
          vidaUtilHacienda: null,
          vidaUtilExperto: null,
          valorEdificioIR: null,
          depreciacionLinealAnual: null,
          valorActualRevaluado: null,
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
    ];

    await db.insert(Sedes).values(dataSede);
    await db.insert(NumeroFincas).values(dataNumeroFinca);
    await db.insert(Construcciones).values(data);
}