import { db } from "~/server/db";
import {
  Edificaciones,
  NumeroFincas,
  Sedes,
  UsosActuales,
} from "~/server/db/schema"; // Asegúrate de importar la tabla que creaste

export async function insertarDatos() {
    const dataSede = {
        nombre: "SEDE ZAPOTE",
    }
  
    const dataNumeroFinca = { 
        numero: "SJ-287792-77" 
    };

    const data = [
        {
          codigoEdificio: "Z-01",
          sede: 5,
          esRenovacion: false,
          nombre: "CET (Incluye remodelación, ducto y ascensor 2011, 2 Niveles)) ",
          fechaConstruccion: 1995,
          noFinca: 8,
          m2Construccion: 1265.0,
          valorDolarPorM2: "1056.36",
          valorColonPorM2: "649502.946",
          edadAl2021: 26,
          vidaUtilHacienda: 50,
          vidaUtilExperto: 30,
          valorEdificioIR: "1336295.4",
          depreciacionLinealAnual: "26725.908",
          valorActualRevaluado: "801777.24",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "Z-01",
          sede: 5,
          esRenovacion: false,
          nombre: "Aceras perimetrales",
          fechaConstruccion: 1995,
          noFinca: 8,
          m2Construccion: 222.0,
          valorDolarPorM2: "30.54",
          valorColonPorM2: "18777.519",
          edadAl2021: 26,
          vidaUtilHacienda: 15,
          vidaUtilExperto: 5,
          valorEdificioIR: "6779.88",
          depreciacionLinealAnual: "451.992",
          valorActualRevaluado: "2259.96",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "Z-01",
          sede: 5,
          esRenovacion: false,
          nombre: "Porción de Zonas Verdes",
          fechaConstruccion: 1995,
          noFinca: 8,
          m2Construccion: 174.0,
          valorDolarPorM2: "3.4",
          valorColonPorM2: "2090.4900000000002",
          edadAl2021: 26,
          vidaUtilHacienda: 10,
          vidaUtilExperto: 5,
          valorEdificioIR: "591.6",
          depreciacionLinealAnual: "59.160000000000004",
          valorActualRevaluado: "295.8",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "Z-01",
          sede: 5,
          esRenovacion: false,
          nombre: "Terreno (Huella)",
          fechaConstruccion: 1995,
          noFinca: 8,
          m2Construccion: 632.5,
          valorDolarPorM2: "381.4627335176681",
          valorColonPorM2: "234542.36170333822",
          edadAl2021: null,
          vidaUtilHacienda: null,
          vidaUtilExperto: null,
          valorEdificioIR: null,
          depreciacionLinealAnual: null,
          valorActualRevaluado: null,
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "Z-02",
          sede: 5,
          esRenovacion: false,
          nombre: "EDIFICIO DE AULAS (ANTIGUO CONICIT)(No se incluye remodelación 2019)( 2 Niveles)",
          fechaConstruccion: 1995,
          noFinca: 8,
          m2Construccion: 600.0,
          valorDolarPorM2: "924.0",
          valorColonPorM2: "568121.4",
          edadAl2021: 26,
          vidaUtilHacienda: 50,
          vidaUtilExperto: 30,
          valorEdificioIR: "554400",
          depreciacionLinealAnual: "11088",
          valorActualRevaluado: "332640",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "Z-02",
          sede: 5,
          esRenovacion: false,
          nombre: "Aceras perimetrales",
          fechaConstruccion: 1995,
          noFinca: 8,
          m2Construccion: 120.0,
          valorDolarPorM2: "30.54",
          valorColonPorM2: "18777.519",
          edadAl2021: 26,
          vidaUtilHacienda: 15,
          vidaUtilExperto: 5,
          valorEdificioIR: "3664.7999999999997",
          depreciacionLinealAnual: "244.32",
          valorActualRevaluado: "1221.6",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "Z-02",
          sede: 5,
          esRenovacion: false,
          nombre: "Porción de Zonas Verdes",
          fechaConstruccion: 1995,
          noFinca: 8,
          m2Construccion: 76.5,
          valorDolarPorM2: "3.4",
          valorColonPorM2: "2090.4900000000002",
          edadAl2021: 26,
          vidaUtilHacienda: 10,
          vidaUtilExperto: 5,
          valorEdificioIR: "260.09999999999997",
          depreciacionLinealAnual: "26.009999999999998",
          valorActualRevaluado: "130.04999999999998",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "Z-02",
          sede: 5,
          esRenovacion: false,
          nombre: "Terreno (Huella)",
          fechaConstruccion: 1995,
          noFinca: 8,
          m2Construccion: 300.0,
          valorDolarPorM2: "487.92388387411563",
          valorColonPorM2: "300000",
          edadAl2021: null,
          vidaUtilHacienda: null,
          vidaUtilExperto: null,
          valorEdificioIR: null,
          depreciacionLinealAnual: null,
          valorActualRevaluado: null,
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "Z-03",
          sede: 5,
          esRenovacion: false,
          nombre: "PARQUEO TECHADO (1 Nivel)",
          fechaConstruccion: 1995,
          noFinca: 8,
          m2Construccion: 311.0,
          valorDolarPorM2: "500.0",
          valorColonPorM2: "307425",
          edadAl2021: 26,
          vidaUtilHacienda: 50,
          vidaUtilExperto: 30,
          valorEdificioIR: "155500",
          depreciacionLinealAnual: "3110",
          valorActualRevaluado: "93300",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "Z-03",
          sede: 5,
          esRenovacion: false,
          nombre: "Aceras perimetrales",
          fechaConstruccion: 1995,
          noFinca: 8,
          m2Construccion: 15.0,
          valorDolarPorM2: "30.54",
          valorColonPorM2: "18777.519",
          edadAl2021: 26,
          vidaUtilHacienda: 15,
          vidaUtilExperto: 5,
          valorEdificioIR: "458.09999999999997",
          depreciacionLinealAnual: "30.54",
          valorActualRevaluado: "152.7",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "Z-03",
          sede: 5,
          esRenovacion: false,
          nombre: "Porción de Zonas Verdes",
          fechaConstruccion: 1995,
          noFinca: 8,
          m2Construccion: 45.0,
          valorDolarPorM2: "3.4",
          valorColonPorM2: "2090.4900000000002",
          edadAl2021: 26,
          vidaUtilHacienda: 10,
          vidaUtilExperto: 5,
          valorEdificioIR: "153",
          depreciacionLinealAnual: "15.3",
          valorActualRevaluado: "76.5",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "Z-03",
          sede: 5,
          esRenovacion: false,
          nombre: "Terreno (Huella)",
          fechaConstruccion: 1995,
          noFinca: 8,
          m2Construccion: 311.0,
          valorDolarPorM2: "482.15998286523563",
          valorColonPorM2: "296456.06546469015",
          edadAl2021: null,
          vidaUtilHacienda: null,
          vidaUtilExperto: null,
          valorEdificioIR: null,
          depreciacionLinealAnual: null,
          valorActualRevaluado: null,
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "Z-04",
          sede: 5,
          esRenovacion: false,
          nombre: "PARQUEOS Y OBRAS EXTERIORES",
          fechaConstruccion: 1996,
          noFinca: 8,
          m2Construccion: 5093.39,
          valorDolarPorM2: "140.0",
          valorColonPorM2: "86079",
          edadAl2021: 25,
          vidaUtilHacienda: 40,
          vidaUtilExperto: 16,
          valorEdificioIR: "713074.6000000001",
          depreciacionLinealAnual: "17826.865",
          valorActualRevaluado: "285229.84",
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "Z-04",
          sede: 5,
          esRenovacion: false,
          nombre: "Aceras perimetrales (No Aplica)",
          fechaConstruccion: 1996,
          noFinca: 8,
          m2Construccion: 0.0,
          valorDolarPorM2: "0.0",
          valorColonPorM2: "0",
          edadAl2021: 0,
          vidaUtilHacienda: 0,
          vidaUtilExperto: 0,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: null,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "Z-04",
          sede: 5,
          esRenovacion: false,
          nombre: "Porción de Zonas Verdes (No Aplica)",
          fechaConstruccion: 1996,
          noFinca: 8,
          m2Construccion: 0.0,
          valorDolarPorM2: "0.0",
          valorColonPorM2: "0",
          edadAl2021: 0,
          vidaUtilHacienda: 0,
          vidaUtilExperto: 0,
          valorEdificioIR: "0",
          depreciacionLinealAnual: "0",
          valorActualRevaluado: "0",
          anoDeRevaluacion: null,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          codigoEdificio: "Z-04",
          sede: 5,
          esRenovacion: false,
          nombre: "Terreno (Huella)",
          fechaConstruccion: 1996,
          noFinca: 8,
          m2Construccion: 5093.39,
          valorDolarPorM2: "191.6416070535294",
          valorColonPorM2: "117830.84209686257",
          edadAl2021: null,
          vidaUtilHacienda: null,
          vidaUtilExperto: null,
          valorEdificioIR: null,
          depreciacionLinealAnual: null,
          valorActualRevaluado: null,
          anoDeRevaluacion: 2021,
          usoActual: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
    ];


    await db.insert(Sedes).values(dataSede);
    await db.insert(NumeroFincas).values(dataNumeroFinca);
    await db.insert(Edificaciones).values(data);
}